# Rubric judge creates nuggets first, then judges using them
judge_class: "trec25.judges.rubric.rubric_autojudge.RubricJudge"

judge_uses_nuggets: true   
nugget_depends_on_responses: false
judge: false # true   # implied
create_nuggets: true  # implied
augment_report: true

settings:
  filebase: "{_name}"
  max_nuggets_per_topic: 20
  stop_collecting_at_nuggets_per_topic: 20

nugget_settings:
  prompt: "minimal"

judge_settings:
  grade_threshold: 4


variants:
  web:
    nugget_settings:
      prompt: "web"

  prefnugget:
    nugget_settings:
      prompt: "IterativeGenerateNuggetQuestionsReportRequest"