# Rubric judge creates nuggets first, then judges using them
nugget_class: "trec25.judges.ground_rubric.groundnugget_judge:GroundNuggetJudge"
judge_class: "trec25.judges.prefnugget.prefnugget_judge:PrefNuggetJudge"

create_nuggets: true
judge: true
judge_uses_nuggets: true
nugget_depends_on_responses: true  # parametric - no responses needed for nugget creation


settings:
  filebase: "ground-{_name}"
  num_others: 4
  num_pivot: 0
  no_dupes: true
  #
  pref_judge: "ties_allowed"  # must_decide | ties_allowed
  
nugget_settings:
  num_others: 4
  num_pivot: 0
  no_dupes: true
  on_missing_evals: fix_aggregate
  iterative_nuggets: true
  max_nuggets_per_topic: 20
  stop_collecting_at_nuggets_per_topic: 20
  gen_batch_num_per_query: 2
  max_pairs_considered: 100
  nugget_gen_order: both
  max_questions_per_pair: 2
  random_pairs: false
  
judge_settings:
  grade_threshold: 4
  grade_text: "response"  # "response" | "document" | "document_paragraphs"


variants:

  ground-response:
    judge_settings:
      grade_text: "response"  # "response" | "document" | "document_paragraphs"

  ground-docs:
    judge_settings:
      grade_text: "document_paragraphs"  # "response" | "document" | "document_paragraphs"


  ground-random-response:
    nugget_settings:
      random_pairs: true
    judge_settings:
      grade_text: "response"  # "response" | "document" | "document_paragraphs"

  ground-random-docs:
    nugget_settings:
      random_pairs: true
    judge_settings:
      grade_text: "document_paragraphs"  # "response" | "document" | "document_paragraphs"

