# Direct Prompt Judge Workflow Configuration

# Judge class for dynamic loading
judge_class: "trec26.judges.direct_prompt.direct_prompt_judge.DirectPromptJudge"

# Lifecycle: create qrels → judge
create_nuggets: false
create_qrels: true   # LLM grades passages first using prompts
judge: true          # Then aggregates to leaderboard

# Data flow
judge_uses_qrels: true   # Judge needs qrels from create_qrels()
judge_uses_nuggets: false
qrels_uses_nuggets: false

# Settings
settings:
  filebase: "{_name}"

# Qrels creation settings
qrels_settings:
  filebase: "{_name}"

# Judge settings
judge_settings:
  # Topic format: auto (default), ragtime, dragun, or rag
  topic_format: auto
  relevance_threshold: 2  # Grade >= 2 is "relevant"
  filebase: "{_name}"

# Variants for different thresholds
variants:
  strict:
    judge_settings:
      relevance_threshold: 3  # Only grade 3 is relevant

  lenient:
    judge_settings:
      relevance_threshold: 1  # Grade >= 1 is relevant
