# Preferecnce judge does not use nuggets
judge_uses_nuggets: false
nugget_depends_on_responses: false
judge: true   # implied
create_nuggets: false  # implied
augment_report: true  # judge modifies Report.evaldata, save to {filebase}.responses.jsonl

settings:
  filebase: "{_name}"
  on_missing_evals: "fix_aggregate"


judge_settings:
   num_others: 8
   num_pivot: 0

variants:
  eightzero:
    judge_settings:
      num_others: 8
      num_pivot: 0

  fourthree:
    judge_settings:
      num_others: 4
      num_pivot: 3

  zerotwo:
    judge_settings:
      num_others: 0
      num_pivot: 2
  
