# PrefNuggetJudge: Extract differentiating nuggets from preference comparisons
# Requires responses with PrefJudge evaldata (run PrefJudge with --augment-report first)

judge_uses_nuggets: true
nugget_depends_on_responses: true  # Need evaldata from PrefJudge
judge: true                       # No leaderboard output
create_nuggets: true               # Primary purpose: create nuggets
augment_report: false

settings:
  filebase: "{_name}"
  num_others: 4
  num_pivot: 0
  no_dupes: true
  on_missing_evals: "fix_aggregate"
  # 
  iterative_nuggets: false
  max_nuggets_per_topic: -1
  stop_collecting_at_nuggets_per_topic: 20
  gen_batch_num_per_query: 2
  max_pairs_considered: -1
  nugget_gen_order: "both"
  pref_judge: "must_decide"  # must_decide | ties_allowed

nugget_settings:
  max_questions_per_pair: 5

judge_settings:
  grade_threshold: 4

variants:
  fourzero:
    nugget_settings:
      num_others: 4
      num_pivot: 0

  twozero:
    nugget_settings:
      num_others: 2
      num_pivot: 0
  test:
    nugget_settings:
      num_others: 0
      num_pivot: 1


  iterative-small:
    iterative_nuggets: true
    num_others: 4
    num_pivot: 0
  subtle:
    iterative_nuggets: true
    max_nuggets_per_topic: 20
    stop_collecting_at_nuggets_per_topic: 20
    
  iter20q:
    iterative_nuggets: true
    nugget_gen_order: "first"
    pref_judge: "must_decide"  # must_decide | ties_allowed
    max_pairs_considered: 100
    gen_batch_num_per_query: 2
    max_nuggets_per_topic: 20
    stop_collecting_at_nuggets_per_topic: 20
    num_others: 4
    num_pivot: 0
    no_dupes: true
    on_missing_evals: "fix_aggregate"
    nugget_settings:
      max_questions_per_pair: 5
    judge_settings:
      grade_threshold: 4

  iter20both:
    iterative_nuggets: true
    nugget_gen_order: "both"
    pref_judge: "must_decide"  # must_decide | ties_allowed
    gen_batch_num_per_query: 2
    max_pairs_considered: 100
    max_nuggets_per_topic: 20
    stop_collecting_at_nuggets_per_topic: 20
    num_others: 4
    num_pivot: 0
    no_dupes: true
    on_missing_evals: "fix_aggregate"
    nugget_settings:
      max_questions_per_pair: 5
    judge_settings:
      grade_threshold: 4

  iter20bothties:
    iterative_nuggets: true
    nugget_gen_order: "both"
    pref_judge: "ties_allowed"  # must_decide | ties_allowed
    gen_batch_num_per_query: 2
    max_pairs_considered: 100
    max_nuggets_per_topic: 20
    stop_collecting_at_nuggets_per_topic: 20
    num_others: 4
    num_pivot: 0
    no_dupes: true
    on_missing_evals: "fix_aggregate"
    nugget_settings:
      max_questions_per_pair: 5
    judge_settings:
      grade_threshold: 4